import { pdfService, COLORS } from '../pdf-service';

interface NormAnalysis {
  name: string;
  pillar: string;
  status: 'conforme' | 'partiel' | 'non_conforme';
  severity: 'critique' | 'majeur' | 'mineur' | 'info';
  finding: string;
  recommendation: string;
}

export interface AuditReportData {
  companyName: string;
  date: string;
  score: number;
  normsCompliant: number;
  normsPartial: number;
  normsNonCompliant: number;
  normsTotal: number;
  criticalIssues: number;
  majorIssues: number;
  minorIssues: number;
  executiveSummary: string;
  norms: NormAnalysis[];
  pillars: Array<{ name: string; norms: string[] }>;
}

const LABELS = {
  en: {
    coverTitle: 'PRE-AUDIT REPORT\nCOMPLIANCE',
    coverSubtitle: (total: number) =>
      `${total} norms analyzed across 6 pillars`,
    headerTitle: 'Compliance Pre-Audit Report',
    executiveSummary: 'Executive Summary',
    thIndicator: 'Indicator',
    thValue: 'Value',
    globalScore: 'Global score',
    normsCompliant: 'Compliant norms',
    partiallyCompliant: 'Partially compliant',
    nonCompliant: 'Non-compliant',
    criticalIssues: 'Critical issues',
    majorIssues: 'Major issues',
    minorIssues: 'Minor issues',
    dashboard: 'Dashboard',
    statusConforme: 'Compliant',
    statusPartiel: 'Partial',
    statusNonConforme: 'Non-compliant',
    severityCritique: 'CRITICAL',
    severityMajeur: 'MAJOR',
    severityMineur: 'MINOR',
    severityInfo: 'INFO',
    thNorm: 'Norm',
    thStatus: 'Status',
    thSeverity: 'Severity',
    thFinding: 'Finding',
    thRecommendation: 'Recommendation',
    remediationPlan: 'Remediation plan',
    thHash: '#',
    thPillar: 'Pillar',
    thCorrectiveAction: 'Corrective action',
    thDeadline: 'Deadline',
    deadline1Month: '1 month',
    deadline3Months: '3 months',
    deadline6Months: '6 months',
    methodology: 'Methodology',
    methodologyText: (total: number) =>
      `This pre-audit report was generated by the GreenEcoGenius analysis engine. The evaluation covers ${total} norms from the reference framework across 6 compliance pillars.\n\nPublisher: GreenEcoGenius, Inc. (Delaware, USA) · GreenEcoGenius OU (Estonia) — greenecogenius.tech`,
    evaluationGrid:
      'Evaluation grid:\n- Compliant: The requirement is fully met with up-to-date documentation\n- Partially compliant: Elements are in place but gaps remain\n- Non-compliant: The requirement is not met, corrective action required',
    severityLevels:
      'Severity levels:\n- Critical: Immediate legal risk, action within 1 month\n- Major: Significant risk, action within 3 months\n- Minor: Improvement recommended, action within 6 months\n- Info: Compliant, continuous monitoring',
    disclaimer:
      'This pre-audit is indicative and does not replace a certified audit by an accredited body.',
  },
  fr: {
    coverTitle: 'RAPPORT DE PRE-AUDIT\nDE CONFORMITE',
    coverSubtitle: (total: number) => `${total} normes analysees sur 6 piliers`,
    headerTitle: 'Rapport de Pre-Audit de Conformite',
    executiveSummary: 'Synthese executive',
    thIndicator: 'Indicateur',
    thValue: 'Valeur',
    globalScore: 'Score global',
    normsCompliant: 'Normes conformes',
    partiallyCompliant: 'Partiellement conformes',
    nonCompliant: 'Non conformes',
    criticalIssues: 'Points critiques',
    majorIssues: 'Points majeurs',
    minorIssues: 'Points mineurs',
    dashboard: 'Tableau de bord',
    statusConforme: 'Conforme',
    statusPartiel: 'Partiel',
    statusNonConforme: 'Non conforme',
    severityCritique: 'CRITIQUE',
    severityMajeur: 'MAJEUR',
    severityMineur: 'MINEUR',
    severityInfo: 'INFO',
    thNorm: 'Norme',
    thStatus: 'Statut',
    thSeverity: 'Severite',
    thFinding: 'Constat',
    thRecommendation: 'Recommandation',
    remediationPlan: 'Plan de remediation',
    thHash: '#',
    thPillar: 'Pilier',
    thCorrectiveAction: 'Action corrective',
    thDeadline: 'Echeance',
    deadline1Month: '1 mois',
    deadline3Months: '3 mois',
    deadline6Months: '6 mois',
    methodology: 'Methodologie',
    methodologyText: (total: number) =>
      `Ce rapport de pre-audit a ete genere par le moteur d'analyse GreenEcoGenius. L'evaluation couvre les ${total} normes du referentiel reparties en 6 piliers de conformite.\n\nEditeur : GreenEcoGenius OU (Estonie) · GreenEcoGenius, Inc. (Delaware, USA) — greenecogenius.tech`,
    evaluationGrid:
      "Grille d'evaluation :\n- Conforme : L'exigence est pleinement respectee avec documentation a jour\n- Partiellement conforme : Des elements sont en place mais des lacunes subsistent\n- Non conforme : L'exigence n'est pas satisfaite, action corrective requise",
    severityLevels:
      'Niveaux de severite :\n- Critique : Risque legal immediat, action sous 1 mois\n- Majeur : Risque significatif, action sous 3 mois\n- Mineur : Amelioration recommandee, action sous 6 mois\n- Info : Conforme, surveillance continue',
    disclaimer:
      'Ce pre-audit est indicatif et ne remplace pas un audit certifie par un organisme accredite.',
  },
} as const;

type Locale = keyof typeof LABELS;

function statusLabel(status: string, labels: (typeof LABELS)[Locale]): string {
  switch (status) {
    case 'conforme':
      return labels.statusConforme;
    case 'partiel':
      return labels.statusPartiel;
    case 'non_conforme':
      return labels.statusNonConforme;
    default:
      return status;
  }
}

function severityLabel(
  severity: string,
  labels: (typeof LABELS)[Locale],
): string {
  switch (severity) {
    case 'critique':
      return labels.severityCritique;
    case 'majeur':
      return labels.severityMajeur;
    case 'mineur':
      return labels.severityMineur;
    default:
      return labels.severityInfo;
  }
}

export function generateAuditReportPDF(
  data: AuditReportData,
  locale: string = 'fr',
): ArrayBuffer {
  const labels =
    LABELS[(locale as Locale) in LABELS ? (locale as Locale) : 'fr'];
  const doc = pdfService.createDocument();
  const headerTitle = labels.headerTitle;

  // Cover page
  pdfService.addCoverPage(doc, {
    title: labels.coverTitle,
    subtitle: labels.coverSubtitle(data.normsTotal),
    organization: data.companyName,
    date: data.date,
    score: `${data.score}%`,
    locale,
  });

  // Page 2: Executive summary
  let y = pdfService.addNewPageWithHeader(doc, headerTitle);

  y = pdfService.addSectionTitle(doc, labels.executiveSummary, y);
  y = pdfService.addParagraph(doc, data.executiveSummary, 15, y, 180);

  y += 5;

  // Summary table
  y = pdfService.addTable(
    doc,
    y,
    [labels.thIndicator, labels.thValue],
    [
      [labels.globalScore, `${data.score}%`],
      [labels.normsCompliant, `${data.normsCompliant} / ${data.normsTotal}`],
      [labels.partiallyCompliant, `${data.normsPartial}`],
      [labels.nonCompliant, `${data.normsNonCompliant}`],
      [labels.criticalIssues, `${data.criticalIssues}`],
      [labels.majorIssues, `${data.majorIssues}`],
      [labels.minorIssues, `${data.minorIssues}`],
    ],
    { title: labels.dashboard },
  );

  pdfService.addFooter(doc, 2, undefined, locale);

  // Pillar detail pages
  let pageNum = 3;

  for (const pillar of data.pillars) {
    const pillarNorms = data.norms.filter((n) => n.pillar === pillar.name);
    if (pillarNorms.length === 0) continue;

    const compliant = pillarNorms.filter((n) => n.status === 'conforme').length;
    const partial = pillarNorms.filter((n) => n.status === 'partiel').length;
    const pillarScore = Math.round(
      ((compliant + partial * 0.5) / pillarNorms.length) * 100,
    );

    y = pdfService.addNewPageWithHeader(doc, headerTitle);

    y = pdfService.addSectionTitle(
      doc,
      `${pillar.name} (${compliant}/${pillarNorms.length} -- ${pillarScore}%)`,
      y,
    );

    pdfService.addScoreGauge(doc, pillarScore, 15, y, '');
    y += 12;

    const rows = pillarNorms.map((n) => [
      n.name,
      statusLabel(n.status, labels),
      severityLabel(n.severity, labels),
      n.finding.substring(0, 60) + (n.finding.length > 60 ? '...' : ''),
      n.recommendation.substring(0, 60) +
        (n.recommendation.length > 60 ? '...' : ''),
    ]);

    y = pdfService.addTable(
      doc,
      y,
      [
        labels.thNorm,
        labels.thStatus,
        labels.thSeverity,
        labels.thFinding,
        labels.thRecommendation,
      ],
      rows,
      {
        columnStyles: {
          0: { cellWidth: 35 },
          1: { cellWidth: 22 },
          2: { cellWidth: 22 },
          3: { cellWidth: 45 },
          4: { cellWidth: 48 },
        },
      },
    );

    pdfService.addFooter(doc, pageNum, undefined, locale);
    pageNum++;
  }

  // Remediation plan
  const nonCompliantNorms = data.norms.filter((n) => n.status !== 'conforme');

  if (nonCompliantNorms.length > 0) {
    y = pdfService.addNewPageWithHeader(doc, headerTitle);
    y = pdfService.addSectionTitle(doc, labels.remediationPlan, y);

    const remRows = nonCompliantNorms.map((n, i) => [
      `${i + 1}`,
      n.name,
      n.pillar,
      severityLabel(n.severity, labels),
      n.recommendation.substring(0, 50) +
        (n.recommendation.length > 50 ? '...' : ''),
      n.severity === 'critique'
        ? labels.deadline1Month
        : n.severity === 'majeur'
          ? labels.deadline3Months
          : labels.deadline6Months,
    ]);

    y = pdfService.addTable(
      doc,
      y,
      [
        labels.thHash,
        labels.thNorm,
        labels.thPillar,
        labels.thSeverity,
        labels.thCorrectiveAction,
        labels.thDeadline,
      ],
      remRows,
      {
        columnStyles: {
          0: { cellWidth: 10 },
          1: { cellWidth: 35 },
          2: { cellWidth: 26 },
          3: { cellWidth: 22 },
          4: { cellWidth: 47 },
          5: { cellWidth: 25 },
        },
      },
    );

    pdfService.addFooter(doc, pageNum, undefined, locale);
    pageNum++;
  }

  // Methodology
  y = pdfService.addNewPageWithHeader(doc, headerTitle);
  y = pdfService.addSectionTitle(doc, labels.methodology, y);

  y = pdfService.addParagraph(
    doc,
    labels.methodologyText(data.normsTotal),
    15,
    y,
    180,
  );

  y = pdfService.addParagraph(doc, labels.evaluationGrid, 15, y, 180);

  y = pdfService.addParagraph(doc, labels.severityLevels, 15, y, 180);

  y += 5;
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.gray);
  doc.setFont('helvetica', 'italic');
  doc.text(labels.disclaimer, 15, y);

  pdfService.addFooter(doc, pageNum, undefined, locale);

  return pdfService.toArrayBuffer(doc);
}
