'use client';

import { useState } from 'react';

import Link from 'next/link';

import {
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Sparkles,
} from 'lucide-react';

import { Badge } from '@kit/ui/badge';
import { Button } from '@kit/ui/button';
import { Card, CardContent } from '@kit/ui/card';
import { Trans } from '@kit/ui/trans';

interface ReportSection {
  titleKey: string;
  completionPct: number;
  sources: Array<'auto' | 'manual' | 'blockchain'>;
  status: 'complete' | 'warning';
  linkHref?: string;
  linkLabelKey?: string;
}

const REPORT_SECTIONS: ReportSection[] = [
  {
    titleKey: 'esg:executiveSummary',
    completionPct: 100,
    sources: ['auto'],
    status: 'complete',
  },
  {
    titleKey: 'esg:carbonBalance',
    completionPct: 94,
    sources: ['auto', 'blockchain'],
    status: 'complete',
    linkHref: '/home/carbon',
    linkLabelKey: 'esg:viewInCarbon',
  },
  {
    titleKey: 'esg:circularEconomy',
    completionPct: 98,
    sources: ['auto', 'blockchain'],
    status: 'complete',
    linkHref: '/home/traceability',
    linkLabelKey: 'esg:viewInTraceability',
  },
  {
    titleKey: 'esg:climateChange',
    completionPct: 72,
    sources: ['auto', 'manual'],
    status: 'warning',
    linkHref: '/home/esg/data-entry',
    linkLabelKey: 'esg:completeFields',
  },
  {
    titleKey: 'esg:socialImpact',
    completionPct: 45,
    sources: ['manual'],
    status: 'warning',
    linkHref: '/home/esg/data-entry',
    linkLabelKey: 'esg:completeFields',
  },
  {
    titleKey: 'esg:governance',
    completionPct: 60,
    sources: ['manual'],
    status: 'warning',
    linkHref: '/home/esg/data-entry',
    linkLabelKey: 'esg:completeFields',
  },
];

const SOURCE_STYLES: Record<
  string,
  { variant: 'default' | 'secondary' | 'outline'; className: string }
> = {
  auto: {
    variant: 'default',
    className:
      'bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:border-emerald-800',
  },
  manual: {
    variant: 'outline',
    className:
      'border-amber-300 text-amber-700 dark:border-amber-700 dark:text-amber-300',
  },
  blockchain: {
    variant: 'secondary',
    className:
      'bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-950/40 dark:text-indigo-300 dark:border-indigo-800',
  },
};

function getSourceLabel(source: string): string {
  switch (source) {
    case 'auto':
      return 'Auto';
    case 'manual':
      return 'Manuel';
    case 'blockchain':
      return 'Blockchain';
    default:
      return source;
  }
}

export function ESGReportAccordion() {
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  return (
    <Card>
      <CardContent className="p-6">
        <h3 className="mb-4 text-lg font-semibold">
          <Trans i18nKey="esg:reportContent" />
        </h3>

        <div className="space-y-2">
          {REPORT_SECTIONS.map((section, index) => {
            const isExpanded = expandedIndex === index;
            const isComplete = section.status === 'complete';

            return (
              <div
                key={section.titleKey}
                className="overflow-hidden rounded-lg border"
              >
                {/* Header row */}
                <button
                  type="button"
                  onClick={() => setExpandedIndex(isExpanded ? null : index)}
                  className="flex w-full items-center justify-between p-4 text-left transition-colors hover:bg-gray-50 dark:hover:bg-gray-900/50"
                >
                  <div className="flex items-center gap-3">
                    {isComplete ? (
                      <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-500" />
                    ) : (
                      <div className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border-2 border-amber-400">
                        <span className="text-[10px] font-bold text-amber-500">
                          !
                        </span>
                      </div>
                    )}
                    <span className="text-sm font-medium">
                      <Trans i18nKey={section.titleKey} />
                    </span>
                    {section.titleKey === 'esg:executiveSummary' && (
                      <Badge
                        variant="outline"
                        className="border-purple-300 text-[10px] text-purple-600"
                      >
                        <Sparkles className="mr-1 h-3 w-3" />
                        <Trans i18nKey="esg:autoGenerated" />
                      </Badge>
                    )}
                  </div>

                  <div className="flex items-center gap-3">
                    <div className="hidden gap-1 sm:flex">
                      {section.sources.map((source) => {
                        const style = SOURCE_STYLES[source];
                        return (
                          <Badge
                            key={source}
                            variant={style?.variant ?? 'outline'}
                            className={`text-[10px] ${style?.className ?? ''}`}
                          >
                            {getSourceLabel(source)}
                          </Badge>
                        );
                      })}
                    </div>
                    <span
                      className={`min-w-[3rem] text-right text-sm font-semibold ${
                        isComplete ? 'text-emerald-600' : 'text-amber-600'
                      }`}
                    >
                      {section.completionPct}%
                    </span>
                    {isExpanded ? (
                      <ChevronDown className="text-muted-foreground h-4 w-4" />
                    ) : (
                      <ChevronRight className="text-muted-foreground h-4 w-4" />
                    )}
                  </div>
                </button>

                {/* Expanded content */}
                {isExpanded && (
                  <div className="border-t bg-gray-50/50 px-4 py-3 dark:bg-gray-900/20">
                    <div className="flex items-center justify-between">
                      <div className="flex-1">
                        {/* Progress bar */}
                        <div className="bg-muted h-2 w-full max-w-md overflow-hidden rounded-full">
                          <div
                            className={`h-full rounded-full transition-all duration-500 ${
                              isComplete ? 'bg-emerald-500' : 'bg-amber-500'
                            }`}
                            style={{
                              width: `${section.completionPct}%`,
                            }}
                          />
                        </div>
                        <div className="mt-2 flex gap-1 sm:hidden">
                          {section.sources.map((source) => {
                            const style = SOURCE_STYLES[source];
                            return (
                              <Badge
                                key={source}
                                variant={style?.variant ?? 'outline'}
                                className={`text-[10px] ${style?.className ?? ''}`}
                              >
                                {getSourceLabel(source)}
                              </Badge>
                            );
                          })}
                        </div>
                      </div>

                      {section.linkHref && section.linkLabelKey && (
                        <Button
                          size="sm"
                          variant={isComplete ? 'ghost' : 'default'}
                          render={
                            <Link href={section.linkHref}>
                              <Trans i18nKey={section.linkLabelKey} />
                              <ChevronRight className="ml-1 h-3 w-3" />
                            </Link>
                          }
                          nativeButton={false}
                        />
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </CardContent>
    </Card>
  );
}
